out_dir: "gs://glm_weights/"

model:
  family: "gpt2"
  n_positions: 40
  n_dims: 10
  n_embd: 256
  n_layer: 12
  n_head: 8

training:
  task: "GLM"
  task_kwargs:
    function_type: "poisson" #Overriden during deployment
    scaling: 0.32
  num_tasks: 250000000
  num_training_examples: null
  data: "gaussian"
  batch_size: 256
  learning_rate: 0.00025
  train_steps: 10000
  save_every_steps: 2000
  keep_every_steps: 2000
  resume_id: null
  curriculum:
    dims:
      start: 10
      end: 10
      inc: 0
      interval: 10000
    points:
      start: 40
      end: 40
      inc: 0
      interval: 10000

wandb:
  project: null
  notes: "ICL GLM training"
  name: "Poisson 0.25 scaling"
  log_every_steps: 10
test_run: false
