out_dir: "gs://glm_weights/"

model:
  family: "gpt2"
  n_positions: 20
  n_dims: 1
  n_embd: 256
  n_layer: 12
  n_head: 8

training:
  task: "GLM"
  task_kwargs:
    function_type: "poisson" #Overriden during deployment
  num_tasks: 250000
  num_training_examples: null
  data: "gaussian"
  batch_size: 256
  learning_rate: 0.00025
  train_steps: 10000
  save_every_steps: 1000
  keep_every_steps: 2000
  resume_id: null
  curriculum:
    dims:
      start: 1
      end: 1
      inc: 0
      interval: 10000
    points:
      start: 20
      end: 20
      inc: 0
      interval: 10000

wandb:
  project: null
  notes: "ICL GLM training"
  name: "Linear"
  log_every_steps: 100

test_run: false
